/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.edu.ijse.thogakade.ui;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.edu.ijse.thogakade.controlle.CashierController;
import lk.edu.ijse.thogakade.controlle.ItemController;
import lk.edu.ijse.thogakade.controller.impl.CashierControllerImpl;
import lk.edu.ijse.thogakade.controller.impl.ItemControllerImpl;
import lk.edu.ijse.thogakade.dto.CashierDTO;
import lk.edu.ijse.thogakade.dto.CustomerDTO;
import lk.edu.ijse.thogakade.dto.ItemDTO;
import lk.edu.ijse.thogakade.dto.OrderDTO;
import lk.edu.ijse.thogakade.dto.OrderDetailDTO;
import lk.edu.ijse.thogakade.dto.OrderDetail_PKDTO;

/**
 *
 * @author USER
 */
public class MainForm extends javax.swing.JFrame {

    private DefaultTableModel dtm;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        dtm = new DefaultTableModel();
        loadItems();
        setDate();
        setTime();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblDateAuto = new javax.swing.JLabel();
        lblAddItem = new javax.swing.JLabel();
        lblAddItem1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtCustomerAddress = new javax.swing.JTextField();
        txtCustomerId = new javax.swing.JTextField();
        txtCustomerContact = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        lblCustomerContact = new javax.swing.JLabel();
        lblCustomerAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoadTable = new javax.swing.JTable();
        lblCustomerName = new javax.swing.JLabel();
        lblCustomerId = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtTotalPrice = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLoadOrder = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtOrderId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblOrderId = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        txtOrderQty = new javax.swing.JTextField();
        txtQTYOnhand = new javax.swing.JTextField();
        cmbPiority = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        btnAddTable = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 700));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setBackground(new java.awt.Color(255, 255, 102));
        lblTime.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        lblTime.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 30));

        lblDateAuto.setBackground(new java.awt.Color(255, 255, 102));
        lblDateAuto.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        lblDateAuto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(lblDateAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 150, 30));

        lblAddItem.setBackground(new java.awt.Color(255, 0, 102));
        lblAddItem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddItem.setForeground(new java.awt.Color(255, 255, 255));
        lblAddItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddItem.setText("Add Customer");
        lblAddItem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblAddItem.setOpaque(true);
        lblAddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddItemMouseClicked(evt);
            }
        });
        jPanel3.add(lblAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 139, 35));

        lblAddItem1.setBackground(new java.awt.Color(255, 0, 102));
        lblAddItem1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddItem1.setForeground(new java.awt.Color(255, 255, 255));
        lblAddItem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddItem1.setText("Add Item");
        lblAddItem1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblAddItem1.setOpaque(true);
        lblAddItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddItem1MouseClicked(evt);
            }
        });
        jPanel3.add(lblAddItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 139, 35));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1080, 70));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1060, 10));

        txtCustomerAddress.setBackground(new java.awt.Color(204, 204, 204));
        txtCustomerAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCustomerAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCustomerAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(txtCustomerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 160, 30));

        txtCustomerId.setBackground(new java.awt.Color(204, 204, 204));
        txtCustomerId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCustomerId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCustomerId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerIdActionPerformed(evt);
            }
        });
        jPanel4.add(txtCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 180, 30));

        txtCustomerContact.setBackground(new java.awt.Color(204, 204, 204));
        txtCustomerContact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCustomerContact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCustomerContact.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(txtCustomerContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, 200, 30));

        txtCustomerName.setBackground(new java.awt.Color(204, 204, 204));
        txtCustomerName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCustomerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCustomerName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });
        jPanel4.add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 180, 30));

        lblCustomerContact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCustomerContact.setText("Customer Contact  :");
        jPanel4.add(lblCustomerContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 140, 30));

        lblCustomerAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCustomerAddress.setText("Customer Address :");
        jPanel4.add(lblCustomerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 140, 30));

        tblLoadTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Id", "Description", "Item Qty", "Unit Price"
            }
        ));
        tblLoadTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoadTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoadTable);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 1030, 90));

        lblCustomerName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCustomerName.setText("Customer Name     :");
        jPanel4.add(lblCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 140, 30));

        lblCustomerId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCustomerId.setText("Customer Id         :");
        jPanel4.add(lblCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 34, 150, 20));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1060, 130));

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setOpaque(true);
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1060, 110));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1080, 270));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTotalPrice.setBackground(new java.awt.Color(204, 204, 204));
        txtTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTotalPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalPrice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(txtTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, 200, 30));

        tblLoadOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Date", "Piority", "Description", "Order Qty ", "Unit Price"
            }
        ));
        jScrollPane2.setViewportView(tblLoadOrder);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 1030, 90));

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Remove");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 100, 30));

        jButton3.setBackground(new java.awt.Color(0, 102, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Update");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 110, 30));

        btnSave.setBackground(new java.awt.Color(0, 102, 255));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel5.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Total Price");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 130, 50));

        txtOrderId.setBackground(new java.awt.Color(204, 204, 204));
        txtOrderId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtOrderId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOrderId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(txtOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 140, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Order Date");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 120, 30));

        lblOrderId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOrderId.setText("Order Id");
        jPanel5.add(lblOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 120, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Description   ");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 30));

        txtDate.setBackground(new java.awt.Color(204, 204, 204));
        txtDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 160, 30));

        txtDesc.setBackground(new java.awt.Color(204, 204, 204));
        txtDesc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDesc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDesc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 140, 30));

        txtOrderQty.setBackground(new java.awt.Color(204, 204, 204));
        txtOrderQty.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtOrderQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOrderQty.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtOrderQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderQtyActionPerformed(evt);
            }
        });
        jPanel5.add(txtOrderQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 160, 30));

        txtQTYOnhand.setBackground(new java.awt.Color(204, 204, 204));
        txtQTYOnhand.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtQTYOnhand.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQTYOnhand.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(txtQTYOnhand, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 120, 30));

        cmbPiority.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbPiority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low  ", "High", "Midium", " " }));
        cmbPiority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPiorityActionPerformed(evt);
            }
        });
        jPanel5.add(cmbPiority, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 120, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Piority");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Qty On Hand  ");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 110, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Order Qty :");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 150, 30));

        txtprice.setBackground(new java.awt.Color(204, 204, 204));
        txtprice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtprice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 170, 30));

        btnAddTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddTable.setText("Add Order To Table");
        btnAddTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTableActionPerformed(evt);
            }
        });
        jPanel5.add(btnAddTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 60, 160, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Unit Price    :");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 110, 30));

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setOpaque(true);
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1060, 90));

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1060, 200));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 1080, 330));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTableActionPerformed
        dtm = (DefaultTableModel) tblLoadOrder.getModel();
        Object[] rowdata = {txtDate.getText(), cmbPiority.getSelectedItem(), txtOrderQty.getText(), txtprice.getText(), txtDesc.getText()};
        if (!txtDate.getText().isEmpty() && !txtDesc.getText().isEmpty() && !txtQTYOnhand.getText().isEmpty() && !txtOrderQty.getText().isEmpty() && !txtprice.getText().isEmpty()) {
            dtm.addRow(rowdata);
        } else {
            JOptionPane.showMessageDialog(this, "Fill All text Fields");
        }

        txtQTYOnhand.setText("");
        txtOrderQty.setText("");
        txtprice.setText("");
        txtDesc.setText("");
    }//GEN-LAST:event_btnAddTableActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            ItemController itemController = new ItemControllerImpl();
            CashierController cachierController = new CashierControllerImpl();

            CustomerDTO customer = new CustomerDTO();
            customer.setCid(txtCustomerId.getText());
            customer.setName(txtCustomerName.getText());
            customer.setAddress(txtCustomerAddress.getText());
            customer.setContact(txtCustomerContact.getText());

            OrderDTO orders = new OrderDTO();
            orders.setDate(txtDate.getText());
            orders.setPriority(cmbPiority.getSelectedItem().toString());

            ArrayList<OrderDetailDTO> orderDetaillist = new ArrayList<>();
            for (int i = 0; i < tblLoadOrder.getRowCount(); i++) {
                try {
                    ItemDTO item = itemController.getItemByDescription(tblLoadOrder.getValueAt(i, 4).toString());
                    item.setQty_on_hand(Integer.parseInt(tblLoadTable.getValueAt(i, 2).toString()) - Integer.parseInt(tblLoadOrder.getValueAt(i, 2).toString()));


                    OrderDetailDTO orderDetail = new OrderDetailDTO();
                    orderDetail.setOrder_qty(Integer.parseInt(tblLoadOrder.getValueAt(i, 2).toString()));
                    orderDetail.setUnitprice(Double.parseDouble(tblLoadOrder.getValueAt(i, 3).toString()));
                    orderDetail.setItemDTO(item);
                    orderDetail.setOrderDTO(orders);
                    orderDetail.setOrderDetail_PKdto(new OrderDetail_PKDTO(item.getItemId(), orders.getOid()));

                    orderDetaillist.add(orderDetail);
                } catch (Exception ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            CashierDTO cashierDTO = new CashierDTO();
            cashierDTO.setCustomerDTO(customer);
            cashierDTO.setOrderDTO(orders);
            cashierDTO.setOrderdetaillist(orderDetaillist);

            boolean add = cachierController.placeOrder(cashierDTO);

            if (add) {
                JOptionPane.showMessageDialog(this,"Added Success Order");
                //System.out.println("Added Success");
                loadItems();
            } else {
                JOptionPane.showMessageDialog(this,"Somthing Not Added Order");
                //System.out.println("Added Fail");
            }
            dtm = (DefaultTableModel) tblLoadOrder.getModel();
            dtm.setRowCount(0);
            txtCustomerId.setText("");
            txtCustomerName.setText("");
            txtCustomerAddress.setText("");
            txtCustomerContact.setText("");
            txtDate.setText("");
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerIdActionPerformed

    private void cmbPiorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPiorityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPiorityActionPerformed

    private void tblLoadTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoadTableMouseClicked
        txtQTYOnhand.setText(tblLoadTable.getValueAt(tblLoadTable.getSelectedRow(), 2).toString());
        txtprice.setText(tblLoadTable.getValueAt(tblLoadTable.getSelectedRow(), 3).toString());
        txtDesc.setText(tblLoadTable.getValueAt(tblLoadTable.getSelectedRow(), 1).toString());
        
    }//GEN-LAST:event_tblLoadTableMouseClicked

    private void lblAddItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddItem1MouseClicked
        //this.dispose();
        new ItemForm().setVisible(true);
    }//GEN-LAST:event_lblAddItem1MouseClicked

    private void lblAddItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddItemMouseClicked
        new CustomerForm().setVisible(true);
    }//GEN-LAST:event_lblAddItemMouseClicked

    private void txtOrderQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderQtyActionPerformed
        String description = txtDesc.getText();
        double unitPrice = Double.parseDouble(txtprice.getText());
       double qty = Double.parseDouble(txtQTYOnhand.getText());
      
        String orderId = txtOrderId.getText();

        for (int i = 0; i < dtm.getRowCount(); i++) {
            int code = (int) dtm.getValueAt(i, 1);
            if (orderId==description) {
                double quantity = (double) dtm.getValueAt(i, 3);
                qty += quantity;
                dtm.removeRow(i);

            }
        }
        double amount = unitPrice * qty;
         amount+= amount;
        txtTotalPrice.setText("" + amount);

        qty = Double.parseDouble(txtQTYOnhand.getText());

        qty -= Integer.parseInt(txtOrderQty.getText());
        txtOrderQty.setText(" " + qty);
        Object ob[] = {orderId, description, qty, unitPrice};
        dtm.addRow(ob);
    }//GEN-LAST:event_txtOrderQtyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTable;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbPiority;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAddItem;
    private javax.swing.JLabel lblAddItem1;
    private javax.swing.JLabel lblCustomerAddress;
    private javax.swing.JLabel lblCustomerContact;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDateAuto;
    private javax.swing.JLabel lblOrderId;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTable tblLoadOrder;
    private javax.swing.JTable tblLoadTable;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerContact;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JTextField txtOrderQty;
    private javax.swing.JTextField txtQTYOnhand;
    private javax.swing.JTextField txtTotalPrice;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables

    
    private void loadItems() {
        dtm = (DefaultTableModel) tblLoadTable.getModel();
        try {
            ItemController itemController = new ItemControllerImpl();
//            dtm = (DefaultTableModel) tblLoadTable.getModel();
            dtm.setRowCount(0);
            List<ItemDTO> itemdtos = itemController.viewItems();
            for (ItemDTO item1 : itemdtos) {
                Object[] rowdata = {item1.getItemId(), item1.getDescription(), item1.getQty_on_hand(), item1.getUnitprice()};
                dtm.addRow(rowdata);
            }
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setDate() {
        java.util.Date d = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String formateDate = df.format(d);
        lblDateAuto.setText(formateDate);
        txtDate.setText(formateDate);
    }

    private void setTime() {
        new Thread(new Runnable() {
            Date d = new Date();

            @Override
            public void run() {
                SimpleDateFormat sdf = new SimpleDateFormat("HH : mm : ss");
                String format = sdf.format(d);
                lblTime.setText(format);
                setTime();
            }
        }).start();
    }

//    private double totalPrice() {
//        double total = 0;
//        for (int i = 0; i < tblLoadOrder.getRowCount(); i++) {
//            total += Integer.parseInt(tblLoadOrder.getValueAt(i, 2).toString()) * Double.parseDouble(tblLoadOrder.getValueAt(i, 3).toString());
//        }
//        return total;
//    }
//    
}
